# Evaluation Configuration
# ====================
# 
# This file contains configuration parameters for the evaluation pipeline.

# === Dataset Configuration ===
dataset:
  path: "C:\\Users\\dicla\\Research_Internship_Under_Dr_Rakesh_Matam\\Project_3\\dataset\\combined_dataset_short_balanced_encoded_normalised.csv"
  test_samples_per_class: 10000  # Number of test samples to extract for each class

# === Model Paths ===
models:
  gru:
    path: "C:\\Users\\dicla\\Research_Internship_Under_Dr_Rakesh_Matam\\Project_3\\GRU\\models\\saved_Models\\gru_experiment1_final.keras"
    type: "keras"
  lstm:
    path: "C:\\Users\\dicla\\Research_Internship_Under_Dr_Rakesh_Matam\\Project_3\\LSTM\\models\\saved_Models\\experiment2_final.keras"
    type: "keras"
  random_forest:
    path: "C:\\Users\\dicla\\Research_Internship_Under_Dr_Rakesh_Matam\\Project_3\\RandomForestClassifier\\models\\saved_Models\\random_forest_model_final_20250913_182351.joblib"
    type: "joblib"
  voting_ensemble:
    path: "C:\\Users\\dicla\\Research_Internship_Under_Dr_Rakesh_Matam\\Project_3\\RandomForestClassifier\\models\\saved_Models\\voting_ensemble_experiment2.joblib"
    type: "joblib"
  xgboost:
    path: "C:\\Users\\dicla\\Research_Internship_Under_Dr_Rakesh_Matam\\Project_3\\RandomForestClassifier\\models\\saved_Models\\random_forest_experiment3_final_20250913_183256.joblib"  # Placeholder, update if found
    type: "joblib"

# === Class Labels ===
classes:
  - "Recon"
  - "Exploitation"
  - "C&C"
  - "Attack"
  - "Benign"

# === Output Configuration ===
output:
  metrics_dir: "C:\\Users\\dicla\\Research_Internship_Under_Dr_Rakesh_Matam\\Project_3\\evaluate\\results\\metrics"
  plots_dir: "C:\\Users\\dicla\\Research_Internship_Under_Dr_Rakesh_Matam\\Project_3\\evaluate\\results\\plots"
  log_dir: "C:\\Users\\dicla\\Research_Internship_Under_Dr_Rakesh_Matam\\Project_3\\evaluate\\logs"
  
# === Metrics Configuration ===
metrics:
  - precision
  - recall
  - f1_score
  - roc_auc

# === Plots Configuration ===
plots:
  - confusion_matrix
  - roc_curve